### ISSUE TITLE
Добавить TODO в README.md

### ISSUE THREAD

**Issue by capricornusx** [capricornusx/grow#1]
Шаблон:
- [ ] Разработать ТЗ :exclamation:
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
